name: BetterFood
version: 1.2.0
author: MagmaGuy
main: com.magmaguy.betterfood.BetterFood
api-version: 1.14
permissions:
  betterfood.user:
    description: Makes players automatically eat crafted / cooked food that is in their inventories when sufficiently hungry