name: BetterFood
version: 1.4.2
authors:
  - MagmaGuy
  - borkmaster12
main: com.magmaguy.betterfood.BetterFood
api-version: '1.21.4'
permissions:
  betterfood.user:
    description: Makes players automatically eat crafted / cooked food that is in their inventories when sufficiently hungry
    default: true
  betterfood.admin:
    description: Allows admins to download BetterFood plugin updates
    default: op
commands:
  betterfood:
    aliases: bf
    description: Use to set betterfood plugin options
    usage: /<command>
